#!/bin/bash

BOOTSTRAP_REPO_URL="https://github.com/liamdawson/mach-prov"
BOOTSTRAP_REPO_TAR="https://github.com/liamdawson/mach-prov/archive/master.tar.gz"
BOOTSTRAP_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

(
  # abort on 1) error output from a line 2) unset variable
  set -e
  set -u

  source $BOOTSTRAP_DIR/utils/output

  if [[ $# -ne 1 ]]
  then
    bstrp_fatal 'expected a path to an os/device configuration pair (e.g. "arch/device-xps15")'
    exit 1
  fi

  BOOSTRAP_OS_DIR="$( cd "$( dirname "$1" )" && pwd )"
  source $1

  device_prepare
)