#!/bin/bash

BOOTSTRAP_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
WORKSPACE_DIR="$HOME/workspace"
SHARED_CONF_DIR="$WORKSPACE_DIR/cdconf"
SHARED_CONF_URL="git@github.com:/liamdawson/cdconf.git"

# global "working on something here" folder
[[ -d "$WORKSPACE_DIR" ]] || mkdir "$WORKSPACE_DIR"

# config I like sharing across machines
[[ -d "$SHARED_CONF_DIR" ]] && (cd "$SHARED_CONF_DIR" && git pull) || git clone "$SHARED_CONF_URL" "$SHARED_CONF_DIR"
"$SHARED_CONF_DIR/home/bin/upstow"

# make sure user shell is ZSH
ZSH_PATH="$(which zsh 2>/dev/null)"
if [[ ! -z "$ZSH_PATH" ]]
then
	# if not currently running zsh, zsh is probably not default shell
	echo "$SHELL" | grep -e "/zsh$" >/dev/null 2>&1 || chsh -s "$ZSH_PATH" "$(whoami)"
else
	echo 'zsh was not found, this is unexpected.'
fi


