#!/bin/bash

export ARCH_PACKAGES="${ARCH_PACKAGES:-} base base-devel vim elinks curl sudo openssh dialog git"

function os_prepare() {
  bstrp_info 'enabling NTP in base install environment...'

  timedatectl set-ntp true

  bstrp_info 'applying localized mirrorlist...'

  cp "${BOOTSTRAP_OS_DIR}/data/mirrorlist" "/etc/pacman.d/mirrorlist"

  bstrp_info 'pacstrapping...'

  bstrp_debug "pacstrap /mnt ${ARCH_PACKAGES}"
  echo "${ARCH_PACKAGES}" | xargs pacstrap /mnt

  bstrp_info 'applying initial fstab...'

  genfstab -U /mnt >> /mnt/etc/fstab

  bstrp_info 'downloading mach-prov onto installed-fileystem (/mach-prov)...'

  mkdir /mnt/mach-prov
  curl -sSL "$BOOTSTRAP_REPO_TAR" | tar xz --directory /mnt/mach-prov --strip-components=1

  bstrp_info 'prepare complete!'
}

function os_install() {
  bstrp_info 'setting timezone...'
  bstrp_debug "setting to $BOOTSTRAP_VAR_TIMEZONE"

  ln -sf "/usr/share/zoneinfo/$BOOTSTRAP_VAR_TIMEZONE" /etc/localtime
  hwclock --systohc

  bstrp_info 'setting locales...'

  sed -Ee 's/^#('"$BOOTSTRAP_VAR_BASE_LOCALE"'.*)$/\1/' /etc/locale.gen -i

  bstrp_info 'generating locales...'

  locale-gen

  bstrp_info 'setting default locale...'

  echo "LANG=$BOOTSTRAP_VAR_DEFAULT_LOCALE" > /etc/locale.conf

  bstrp_info 'setting hostname...'
  bstrp_debug "setting to $BOOTSTRAP_HOSTNAME"

  echo "$BOOTSTRAP_HOSTNAME" > /etc/hostname

  bstrp_info 'setting hosts file...'

  echo '127.0.0.1	localhost' >> /etc/hosts
  echo '::1	localhost' >> /etc/hosts
  echo "127.0.1.1	${BOOTSTRAP_HOSTNAME}.localdomain $BOOTSTRAP_HOSTNAME" >> /etc/hosts

  bstrp_info 'adding default user...'
  bstrp_debug "adding user $BOOTSTRAP_USERNAME"

  useradd -m "$BOOTSTRAP_USERNAME"
  usermod -aG wheel "$BOOTSTRAP_USERNAME"

  bstrp_info 'enabling default sudo configuration...'

  cp "${BOOTSTRAP_OS_DIR}/data/50-wheel-admin" /etc/sudoers.d/50-wheel-admin

  bstrp_info "changing default user's password..."

  passwd "$BOOTSTRAP_USERNAME"
}

function os_install_cleanup() {
  rm -rf /mach-prov
}

function os_update() {
  #ensure required packages are installed:
  sudo pacman --needed --noconfirm -Sy stow zsh

  #ensure my preferred AUR helper is installed and updated
  if [[ -z "$(which trizen 2>/dev/null)" ]]
  then
    OLD_DIR="$(pwd)"
    git clone https://aur.archlinux.org/trizen.git /tmp/trizen
    cd /tmp/trizen
    makepkg -si
    cd "$OLD_DIR"
    rm -rf /tmp/trizen
  else
    trizen -Sy trizen
  fi

  # ensure required AUR packages are installed
  trizen -Sy ttf-roboto-mono

  # ensure preferred fonts are installed
  sudo cp "$BOOTSTRAP_OS_DIR/data/font-config/90-monospace.conf" '/etc/fonts/conf.d/'
}