#!/bin/bash

export ARCH_BASE_PACKAGES="base base-devel vim curl sudo openssh"
export ARCH_DEV_PACKAGES="git stow minicom jdk8-openjdk gdb arm-none-eabi-binutils arm-none-eabi-gdb cmake"
export ARCH_DEV_APP_PACKAGES="firefox-developer-edition"
export ARCH_APP_PACKAGES="${ARCH_DEV_APP_PACKAGES} elinks xfce4-terminal firefox firefox-developer-edition gnome-control-center nautilus gnome-tweak-tool"
export ARCH_GUI_PACKAGES="xorg-server xorg-server-xwayland gdm gnome-shell polkit-gnome network-manager-applet"
export ARCH_FONT_PACKAGES="ttf-roboto noto-fonts noto-fonts-extra noto-fonts-emoji"
export ARCH_MISC_PACKAGES="zsh dialog"
export ARCH_PACKAGES="${ARCH_PACKAGES:-} ${ARCH_BASE_PACKAGES} ${ARCH_DEV_PACKAGES} ${ARCH_APP_PACKAGES} ${ARCH_GUI_PACKAGES} ${ARCH_FONT_PACKAGES} ${ARCH_MISC_PACKAGES}"
export AUR_GUI_PACKAGES="gnome-shell-extension-desk-changer-git"
export AUR_DEV_PACKAGES="openocd"
export AUR_DEV_APP_PACKAGES="jetbrains-toolbox visual-studio-code-bin zeal"
export AUR_FONT_PACKAGES="ttf-roboto-mono"
export AUR_APP_PACKAGES="trizen"
export AUR_MISC_PACKAGES="icu55"
export AUR_PACKAGES="${AUR_GUI_PACKAGES} ${AUR_FONT_PACKAGES} ${AUR_APP_PACKAGES} ${AUR_DEV_PACKAGES} ${AUR_DEV_APP_PACKAGES} ${AUR_MISC_PACKAGES}"
export GNOME_EXTENSIONS="user-theme@gnome-shell-extensions.gcampax.github.com dash-to-panel@jderose9.github.com"

function os_prepare() {
  bstrp_info 'enabling NTP in base install environment...'

  timedatectl set-ntp true

  bstrp_info 'applying localized mirrorlist...'

  cp "${BOOTSTRAP_OS_DIR}/data/mirrorlist" "/etc/pacman.d/mirrorlist"

  bstrp_info 'enabling multilib...'

  cp "${BOOTSTRAP_OS_DIR}/data/pacman.conf" "/etc/pacman.conf"

  bstrp_info 'pacstrapping...'

  bstrp_debug "pacstrap /mnt ${ARCH_PACKAGES}"
  echo "${ARCH_PACKAGES}" | xargs pacstrap /mnt

  bstrp_info 'applying initial fstab...'

  genfstab -U /mnt >> /mnt/etc/fstab

  bstrp_info 'downloading mach-prov onto installed-fileystem (/mach-prov)...'

  mkdir /mnt/mach-prov
  curl -sSL "$BOOTSTRAP_REPO_TAR" | tar xz --directory /mnt/mach-prov --strip-components=1

  bstrp_info 'prepare complete!'
}

function os_install() {
  bstrp_info 'setting timezone...'
  bstrp_debug "setting to $BOOTSTRAP_VAR_TIMEZONE"

  ln -sf "/usr/share/zoneinfo/$BOOTSTRAP_VAR_TIMEZONE" /etc/localtime
  hwclock --systohc

  bstrp_info 'setting locales...'

  sed -Ee 's/^#('"$BOOTSTRAP_VAR_BASE_LOCALE"'.*)$/\1/' /etc/locale.gen -i

  bstrp_info 'generating locales...'

  locale-gen

  bstrp_info 'setting default locale...'

  echo "LANG=$BOOTSTRAP_VAR_DEFAULT_LOCALE" > /etc/locale.conf

  bstrp_info 'setting hostname...'
  bstrp_debug "setting to $BOOTSTRAP_HOSTNAME"

  echo "$BOOTSTRAP_HOSTNAME" > /etc/hostname

  bstrp_info 'setting hosts file...'

  echo '127.0.0.1	localhost' >> /etc/hosts
  echo '::1	localhost' >> /etc/hosts
  echo "127.0.1.1	${BOOTSTRAP_HOSTNAME}.localdomain $BOOTSTRAP_HOSTNAME" >> /etc/hosts

  bstrp_info 'adding default user...'
  bstrp_debug "adding user $BOOTSTRAP_USERNAME"

  useradd -m "$BOOTSTRAP_USERNAME"
  usermod -aG wheel "$BOOTSTRAP_USERNAME"

  bstrp_info 'enabling default sudo configuration...'

  cp "${BOOTSTRAP_OS_DIR}/data/50-wheel-admin" /etc/sudoers.d/50-wheel-admin

  bstrp_info "changing default user's password..."

  passwd "$BOOTSTRAP_USERNAME"
}

function os_install_cleanup() {
  rm -rf /mach-prov
}

function os_update() {
  #ensure required packages are installed:
  echo "$ARCH_PACKAGES" | xargs sudo pacman --needed --noconfirm -Sy 

  #ensure my preferred AUR helper is installed and updated
  if [[ -z "$(which trizen 2>/dev/null)" ]]
  then
    OLD_DIR="$(pwd)"
    git clone https://aur.archlinux.org/trizen.git /tmp/trizen
    cd /tmp/trizen
    makepkg -si
    cd "$OLD_DIR"
    rm -rf /tmp/trizen
  fi

  # ensure preferred AUR packages are installed
  echo "$AUR_PACKAGES" | xargs trizen --needed --noconfirm -Sy 
  
  # ensure preferred fonts are configured
  sudo cp "$BOOTSTRAP_OS_DIR/data/font-config/90-monospace.conf" '/etc/fonts/conf.d/'

  # pull gnome extension install script
  sudo bash -c "curl -sSL 'https://gist.githubusercontent.com/okelet/14bb79ff44e45eee869d444b6a7d68cf/raw/7992b7b6594da76a46c8479a0f03a2c8bd411e6d/gnome-ext-install.sh' > /usr/local/bin/gnome-ext"
  sudo chmod +x /usr/local/bin/gnome-ext
}

function os_post_config_update() {
  gsettings set org.gnome.desktop.screensaver picture-uri "file://$HOME/Pictures/wallpapers/red-highlands-john-towner.jpg"
  gsettings set org.gnome.desktop.background picture-uri "file://$HOME/Pictures/wallpapers/mirrors-edge-faith-shatter.jpg"
}
